CREATE TABLE [TABLE_PEOPLE] (
	PK_PEOPLE_ID integer IDENTITY(1,1) NOT NULL,
	PEOPLE_NAME varchar(100) NOT NULL,
  CONSTRAINT [PK_TABLE_PEOPLE] PRIMARY KEY CLUSTERED
  (
  [PK_PEOPLE_ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TABLE_ADDRESSES] (
	PK_ADDRESS_ID integer IDENTITY(1,1) NOT NULL,
	ADDRESS_LINE_1 varchar(100) NOT NULL,
	ADDRESS_LINE_2 varchar(100) NOT NULL,
	CITY varchar(100) NOT NULL,
	STATE varchar(2) NOT NULL,
	ZIP varchar(5) NOT NULL,
	FK_PEOPLE_ID integer NOT NULL,
  CONSTRAINT [PK_TABLE_ADDRESSES] PRIMARY KEY CLUSTERED
  (
  [PK_ADDRESS_ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TABLE_PHONE] (
	PK_PHONE_ID integer IDENTITY(1,1) NOT NULL,
	PHONE_NUMBER varchar(10) NOT NULL,
	FK_PEOPLE_ID integer NOT NULL,
  CONSTRAINT [PK_TABLE_PHONE] PRIMARY KEY CLUSTERED
  (
  [PK_PHONE_ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

ALTER TABLE [TABLE_ADDRESSES] WITH CHECK ADD CONSTRAINT [TABLE_ADDRESSES_fk0] FOREIGN KEY ([FK_PEOPLE_ID]) REFERENCES [TABLE_PEOPLE]([PK_PEOPLE_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TABLE_ADDRESSES] CHECK CONSTRAINT [TABLE_ADDRESSES_fk0]
GO

ALTER TABLE [TABLE_PHONE] WITH CHECK ADD CONSTRAINT [TABLE_PHONE_fk0] FOREIGN KEY ([FK_PEOPLE_ID]) REFERENCES [TABLE_PEOPLE]([PK_PEOPLE_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TABLE_PHONE] CHECK CONSTRAINT [TABLE_PHONE_fk0]
GO

