
--Display People and their Phone numbers
SELECT PEOPLE_NAME, PHONE_NUMBER
FROM TABLE_PEOPLE
INNER JOIN TABLE_PHONE
	ON PK_PEOPLE_ID = FK_PEOPLE_ID

--Display People and their addresses
SELECT PEOPLE_NAME, 
		ADDRESS_LINE_1 + ' ,' + ADDRESS_LINE_2 + ' ,' + CITY + ' ,' + STATE + ' ,' + ZIP [ADDRESS]
FROM TABLE_ADDRESSES
INNER JOIN TABLE_PEOPLE
	ON FK_PEOPLE_ID = PK_PEOPLE_ID


--Display People and their addresses only if they live in California
SELECT PEOPLE_NAME, 
		ADDRESS_LINE_1 + ' ,' + ADDRESS_LINE_2 + ' ,' + CITY + ' ,' + STATE + ' ,' + ZIP [ADDRESS]
FROM TABLE_ADDRESSES
INNER JOIN TABLE_PEOPLE
	ON FK_PEOPLE_ID = PK_PEOPLE_ID
WHERE STATE = 'CA'

--Show how many people have addresses in each state
SELECT PEOPLE_NAME FROM TABLE_PEOPLE
INNER JOIN (SELECT FK_PEOPLE_ID, 
				COUNT(DISTINCT [STATE]) [STATE_COUNT] FROM TABLE_ADDRESSES 
				GROUP BY FK_PEOPLE_ID
				HAVING COUNT(DISTINCT [STATE]) = (SELECT COUNT(DISTINCT [STATE]) FROM TABLE_ADDRESSES)) List
ON PK_PEOPLE_ID = FK_PEOPLE_ID

--Show the % of people that have multiple Addresses
SELECT CAST((COUNT(PK_PEOPLE_ID) * 100) / (select count(*) from TABLE_PEOPLE) AS VARCHAR) + '%' [PEOPLE_PERCENT]
FROM TABLE_PEOPLE
WHERE PK_PEOPLE_ID IN (SELECT FK_PEOPLE_ID FROM TABLE_ADDRESSES 
						GROUP BY FK_PEOPLE_ID
						HAVING COUNT(PK_ADDRESS_ID) > 1)